### PR TITLE
Adapt to iOS10

### PR DESCRIPTION
**Pull request by wang9262**
Adapt to iOS 10 changes

### CODE REVIEW

**Comment by hstdt** [comment]
on iOS10

> Only opening current app's setting page(UIApplicationOpenSettingsURLString) is allowed.

http://stackoverflow.com/a/37985919/4728060

**Comment by wang9262** [comment]
Our app is using this method(`prefs://xxxx`) to open the `Settings.app`,it works on iOS9 but not iOS10.And we are still not rejected by Apple.And someone tells we should capitalize the first letter for `prefs` which is `Prefs`.So feel free to use this!

**Comment by hstdt** [comment]
@wang9262 
I tried on iOS10,but it doesn't work.

**Comment by wang9262** [comment]
How did you do?

**Comment by hstdt** [comment]
You means using Prefs to avoid rejecting?

**Comment by hstdt** [comment]
And `Prefs:root=WIFI` still  does not open settings.app at my iPad(iOS10).I have no idea that why replacing `prefs` to `Prefs`

**Comment by wang9262** [comment]
No, maybe you misunderstand me.
I said in iOS 10, the previous setting url scheme will not work any more, but if you capitalize like this `Prefs`,It works again.
If you are in China you can see [this Weibo](http://m.weibo.cn/1765732340/EbyothR2G) or this [repo](https://github.com/cyanzhong/app-tutorials/blob/master/prefs.md) for more details. 
I test it in the app named [Pin](https://itunes.apple.com/cn/app/pin-jian-tie-ban-kuo-zhan/id1039643846?mt=8).

**Comment by wang9262** [comment]
As for the reason why capitalizing the first letter works, I'm also curious.

**Comment by hstdt** [comment]
image

I will test on widget after holiday.But I believe it is just a bug on iOS10.0.

**Comment by hstdt** [comment]
For iOS 10+  ,prefix `app-` is necessary.  Readme was updated.

**Pull request closed without merging**
